kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgB4hsgCj6VnsUSP+b2eNUgvEeJcwvrXMxhSPcJ7XAOyUvbFGAA0Ifz+CIrZQVX1ulnK67iQzl/AG8JakTRdmBT3aSSHQy3u0EuT2X5mlWREpsEbKxk1XWEFe3q3Lgb6gggjzl+uMefj2f5dGg92ioNQoyhEpbADjJPhKilpJChjqyvxPxhJGs8baM/o5skK58I+SZ+PKOM5W+U93eL60VbbqrHMM1DxAxGMVaOhFgXsoJtXyRGp9tRJtbm4kEQkhs1sZmzAbb5zZVIA9BC8o9RE1NQY1qPOGyG2zXvRw210ckLIFdbBxX3leUvmMF5+Ugbc8PN/D/B5yp72VuRebatI8sapv7TSFijqF4QmzXmhXOTxszYBJi8IR7AEDoHHEqnHYCByNUGJGVtq7txlupk3XY0ERyccOlfYgD1uzvBB86k+AWZskXBYECHUNDvbqCDmvSoy1UAZ2N5voIV/ySirChk/X2Bhhc/WRoKicrXIggqks/P50VQ4DyQ+JEmATvLbBolIc9H1/ODisXFtYHMTWsk+2t+EM/HFoTSaklh9FTIgLLC0bQcI1c4h4eViRrBcBlZeSpBM+tTaFEslakaSlK6jGXn07cTFIiDhdrtoYBhnaUbo+EvkJaFrGnihFgsb84G4tBE1rzN84yUjvMGQbLfyQQYFPmroOshIahUtZvvm3IoDQEM1rmg8RgA6SPM1BDjj0KNIBQ==
    admin-user: AgAUaExhtBom8OS/1WJg+ExyLvWaiqKoymaBf5qqn6/XA1JFcTnX6JHBZdjRrWHItc/DXMltktFfagH1RvKIk+L+hFHiIXY0fOztmIQ8A4NZhtyhnDj5Oe1Zpe4C31N2sUA+THZBcIeUyMxnhKiUqbk7uO3o9NZxctz3N6lJekGF9Vzji30hDS4kwkojItyV3fHqW/VQWjbzVfvqNr391vjJo6M09q1mhdAys5jLISYDoeEgb80XzyKjkUWhTBAx3BLYywK/LrsPvrH+zH5ij77nTFLt2Uj5CHxQ6hNzrrTC8aUOhyiqXfBC7KQEuGFm84HiJI4mZ3wbykL5CXXFmRkgxEDVZWY9L68ZyeOr89PWRXZv2mQD+XZ/Da+o6MEefWEG+Hht/bDsJm5wZN4zmHjW20Oc9sU9U5FW5AV0xvyUxIEaBbF5L+OWloN6slEslXH7apOGh3YN7/z5YV2s0sogSm8FkZ/jXFuewXW60RtvK69xun80DeGKTOvm6AAMpw/LEAbWK4Kg9OPCED3gU5sLM2ihfhHuYPQaqJzjF7l4uPJ37eaSRg9lETstoOJKk6vrBa8fw84vkfia1pmjFq2DPlZER5AsUXpkAtYDT0cEEqqQA49T3GQE0lij1nc1RWVGjjKSs9X2IfahoNSyS9+dLpfLx1nXeGCpGoq6L6oOhUxO5CxObDLAQudi0yPp8fLdvqUNT9jI6Q==
